#include <iostream>
#include <string>
#include <map>
using std::map;
using std::wstring;
namespace GameData {
	map<wstring, wstring> ItemNameMap = {
		{L"Healing Grape",L"ITM_CSM_0010"},
		{L"Healing Grape (M)",L"ITM_CSM_0020"},
		{L"Healing Grape Bunch",L"ITM_CSM_0030"},
		{L"Shady Grape Bunch",L"ITM_CSM_0031"},
		{L"Inspiriting Plum",L"ITM_CSM_0040"},
		{L"Inspiriting Plum (M)",L"ITM_CSM_0050"},
		{L"Inspiriting Plum Basket",L"ITM_CSM_0060"},
		{L"Shady Inspiriting Plum",L"ITM_CSM_0061"},
		{L"Energizing Pomegranate",L"ITM_CSM_0070"},
		{L"Energizing Pomegranate (M)",L"ITM_CSM_0080"},
		{L"Energizing Pomegranate (L)",L"ITM_CSM_0090"},
		{L"Shady Energizing Pomegranate",L"ITM_CSM_0091"},
		{L"Empowering Lychee",L"ITM_CSM_0220"},
		{L"Empowering Lychee (M)",L"ITM_CSM_0230"},
		{L"Empowering Lychee (L)",L"ITM_CSM_0240"},
		{L"Refreshing Jam",L"ITM_CSM_0100"},
		{L"Reinforcing Jam",L"ITM_CSM_0101"},
		{L"Revitalizing Jam",L"ITM_CSM_0110"},
		{L"Rejuvenating Jam",L"ITM_CSM_0111"},
		{L"Olive of Life",L"ITM_CSM_0120"},
		{L"Olive of Life (M)",L"ITM_CSM_0130"},
		{L"Olive of Life (L)",L"ITM_CSM_0140"},
		{L"Almighty Olive",L"ITM_CSM_0141"},
		{L"Herb of Healing",L"ITM_CSM_0150"},
		{L"Herb of Clamor",L"ITM_CSM_0160"},
		{L"Herb of Light",L"ITM_CSM_0170"},
		{L"Herb of Clarity",L"ITM_CSM_0180"},
		{L"Herb of Awakening",L"ITM_CSM_0190"},
		{L"Herb of Valor",L"ITM_CSM_0200"},
		{L"Herb of Revival",L"ITM_CSM_0210"},
		{L"Herb Elixir",L"ITM_CSM_0211"},
		{L"Bottle of Poison Dust",L"ITM_CSM_0250"},
		{L"Bottle of Blinding Dust",L"ITM_CSM_0260"},
		{L"Bottle of Befuddling Dust",L"ITM_CSM_0270"},
		{L"Bottle of Sleeping Dust",L"ITM_CSM_0280"},
		{L"Bottled Nightmares",L"ITM_CSM_0281"},
		{L"Fire Soulstone",L"ITM_CSM_0290"},
		{L"Fire Soulstone (M)",L"ITM_CSM_0300"},
		{L"Fire Soulstone (L)",L"ITM_CSM_0310"},
		{L"Ice Soulstone",L"ITM_CSM_0320"},
		{L"Ice Soulstone (M)",L"ITM_CSM_0330"},
		{L"Ice Soulstone (L)",L"ITM_CSM_0340"},
		{L"Wind Soulstone",L"ITM_CSM_0380"},
		{L"Wind Soulstone (M)",L"ITM_CSM_0390"},
		{L"Wind Soulstone (L)",L"ITM_CSM_0400"},
		{L"Light Soulstone",L"ITM_CSM_0410"},
		{L"Light Soulstone (M)",L"ITM_CSM_0420"},
		{L"Light Soulstone (L)",L"ITM_CSM_0430"},
		{L"Shadow Soulstone",L"ITM_CSM_0440"},
		{L"Shadow Soulstone (M)",L"ITM_CSM_0450"},
		{L"Shadow Soulstone (L)",L"ITM_CSM_0460"},
		{L"Almighty Soulstone",L"ITM_CSM_0465"},
		{L"Ancient Sentinel Core",L"ITM_CSM_0468"},
		{L"Primeval Horn Elixir",L"ITM_CSM_0469"},
		{L"Ruinous Relic",L"ITM_CSM_0475"},
		{L"Ancient Cursed Talisman",L"ITM_CSM_0476"},
		{L"Decaying Dragon's Essence",L"ITM_CSM_0477"},
		{L"Herb-of-Grace Bud",L"ITM_FLV_0290"},
		{L"Wriggling Root",L"ITM_CSM_0478"},
		{L"Grail of Life",L"ITM_CSM_0479"},
		{L"Nourishing Nut",L"ITM_CSM_0470"},
		{L"Nourishing Nut (M)",L"ITM_CSM_0480"},
		{L"Nourishing Nut (L)",L"ITM_CSM_0490"},
		{L"Invigorating Nut",L"ITM_CSM_0500"},
		{L"Invigorating Nut (M)",L"ITM_CSM_0510"},
		{L"Invigorating Nut (L)",L"ITM_CSM_0520"},
		{L"Fortifying Nut",L"ITM_CSM_0530"},
		{L"Fortifying Nut (M)",L"ITM_CSM_0540"},
		{L"Fortifying Nut (L)",L"ITM_CSM_0550"},
		{L"Magic Nut",L"ITM_CSM_0590"},
		{L"Magic Nut (M)",L"ITM_CSM_0600"},
		{L"Magic Nut (L)",L"ITM_CSM_0610"},
		{L"Resistant Nut",L"ITM_CSM_0620"},
		{L"Resistant Nut (M)",L"ITM_CSM_0630"},
		{L"Resistant Nut (L)",L"ITM_CSM_0640"},
		{L"Sharp Nut",L"ITM_CSM_0650"},
		{L"Sharp Nut (M)",L"ITM_CSM_0660"},
		{L"Sharp Nut (L)",L"ITM_CSM_0670"},
		{L"Slippery Nut",L"ITM_CSM_0680"},
		{L"Slippery Nut (M)",L"ITM_CSM_0690"},
		{L"Slippery Nut (L)",L"ITM_CSM_0700"},
		{L"Critical Nut",L"ITM_CSM_0710"},
		{L"Critical Nut (M)",L"ITM_CSM_0720"},
		{L"Critical Nut (L)",L"ITM_CSM_0730"},
		{L"Light Nut",L"ITM_CSM_0740"},
		{L"Light Nut (M)",L"ITM_CSM_0750"},
		{L"Light Nut (L)",L"ITM_CSM_0760"},
		{L"Scorched Horseshoe",L"ITM_FLV_0010"},
		{L"Stuffed Toy",L"ITM_FLV_0020"},
		{L"Candy",L"ITM_FLV_0030"},
		{L"Glass Marble",L"ITM_FLV_0040"},
		{L"Handkerchief",L"ITM_FLV_0050"},
		{L"Azuki Porridge",L"ITM_FLV_0060"},
		{L"Couple's Pendant",L"ITM_FLV_0080"},
		{L"Hairbrush",L"ITM_FLV_0100"},
		{L"Light Coin Pouch",L"ITM_FLV_0110"},
		{L"Forbidden Elixir",L"ITM_FLV_0120"},
		{L"Chipped Dish",L"ITM_FLV_0130"},
		{L"Crimson Rose",L"ITM_FLV_0140"},
		{L"Bone",L"ITM_FLV_0150"},
		{L"Silk Handkerchief",L"ITM_FLV_0160"},
		{L"Poetry of the Soul",L"ITM_FLV_0170"},
		{L"Rich Ale",L"ITM_FLV_0180"},
		{L"Red Apple",L"ITM_FLV_0190"},
		{L"Complex Tome",L"ITM_FLV_0200"},
		{L"Scrap Iron",L"ITM_FLV_0210"},
		{L"Cog",L"ITM_FLV_0220"},
		{L"Heavy Book",L"ITM_FLV_0230"},
		{L"Rare Cog",L"ITM_FLV_0240"},
		{L"Stone",L"ITM_FLV_0250"},
		{L"STuFfeD ToY",L"ITM_FLV_0260"},
		{L"Small Silver Ore",L"ITM_FLV_0270"},
		{L"Large Silver Ore",L"ITM_FLV_0280"},
		{L"Skystone",L"ITM_FLV_0300"},
		{L"Aged Wine",L"ITM_FLV_0310"},
		{L"Introduction to Trade",L"ITM_FLV_0320"},
		{L"Gold Nugget",L"ITM_FLV_0330"},
		{L"Handmade Rice Ball",L"ITM_FLV_0340"},
		{L"Alrond's Promissory Note",L"ITM_FLV_0350"},
		{L"Dumbbell",L"ITM_FLV_0360"},
		{L"Sunken Gold Statue",L"ITM_FLV_0380"},
		{L"Lump of Silver",L"ITM_FLV_0460"},
		{L"Silver Ingot",L"ITM_FLV_0470"},
		{L"Purse of Hope",L"ITM_FLV_0480"},
		{L"Antique Coin",L"ITM_FLV_0490"},
		{L"Old Cloth",L"ITM_FLV_0510"},
		{L"Raspberry",L"ITM_FLV_0520"},
		{L"Rare Stone",L"ITM_FLV_0530"},
		{L"Vivid Jewel",L"ITM_FLV_0540"},
		{L"Heavy Coin Pouch",L"ITM_FLV_0550"},
		{L"Silver-Filled Pouch",L"ITM_FLV_0560"},
		{L"Antique Coin",L"ITM_FLV_0570"},
		{L"Silver-Rimmed Monocle",L"ITM_FLV_0580"},
		{L"Gold Pocket Watch",L"ITM_FLV_0590"},
		{L"Gold Ring",L"ITM_FLV_0600"},
		{L"Curious Antique",L"ITM_FLV_0610"},
		{L"Dazzling Artwork",L"ITM_FLV_0620"},
		{L"Silver Coin",L"ITM_FLV_0630"},
		{L"Wheat Bread",L"ITM_FLV_0640"},
		{L"Bewitching Perfume",L"ITM_FLV_0650"},
		{L"Empty Coin Pouch",L"ITM_FLV_0660"},
		{L"Handmade Bouquet",L"ITM_FLV_0670"},
		{L"Old Locket",L"ITM_FLV_0680"},
		{L"Silver-Plated Knife",L"ITM_FLV_0690"},
		{L"Homemade Cake",L"ITM_FLV_0700"},
		{L"Exotic Remedy",L"ITM_FLV_0740"},
		{L"Bottled Toxins",L"ITM_FLV_0750"},
		{L"Noxious Needle",L"ITM_FLV_0760"},
		{L"Gold Dust",L"ITM_FLV_0765"},
		{L"Slumber Sage",L"ITM_SLP_0010"},
		{L"Herb of Serenity",L"ITM_SLP_0020"},
		{L"Stylish Nut",L"ITM_CSM_0770"},
		{L"Lousy Rock",L"ITM_FLV_0450"},
		{L"Inventor's Handbook, Volume I",L"ITM_FLV_0500"},
		{L"Conqueror's Sword",L"ITM_EQP_SWD_990"},
		{L"Serpent Slayer",L"ITM_EQP_SWD_330"},
		{L"Battle-Tested Blade",L"ITM_EQP_SWD_300"},
		{L"Lost Tribe's Blade",L"ITM_EQP_SWD_490"},
		{L"Eclipse Edge",L"ITM_EQP_SWD_320"},
		{L"Sword of Oaths",L"ITM_EQP_SWD_410"},
		{L"Divine Splendor",L"ITM_EQP_SWD_470"},
		{L"Expert's Obsidian Edge",L"ITM_EQP_SWD_480"},
		{L"Giant's Blade",L"ITM_EQP_SWD_210"},
		{L"Forbidden Blade",L"ITM_EQP_SWD_290"},
		{L"Skypiercer",L"ITM_EQP_SWD_280"},
		{L"Sanctum Sword",L"ITM_EQP_SWD_190"},
		{L"Keepsake Sword",L"ITM_EQP_SWD_240"},
		{L"Hypno Sword",L"ITM_EQP_SWD_170"},
		{L"Evil Slayer",L"ITM_EQP_SWD_420"},
		{L"Starsplitter",L"ITM_EQP_SWD_250"},
		{L"Ogre's Bane",L"ITM_EQP_SWD_220"},
		{L"Bastard Sword",L"ITM_EQP_SWD_230"},
		{L"Great Blade",L"ITM_EQP_SWD_150"},
		{L"Guardian's Iceblade",L"ITM_EQP_SWD_360"},
		{L"Bloodsucker",L"ITM_EQP_SWD_340"},
		{L"Soulsucker",L"ITM_EQP_SWD_440"},
		{L"Aegis Sword",L"ITM_EQP_SWD_200"},
		{L"Master Rod",L"ITM_EQP_SWD_370"},
		{L"Firestarter",L"ITM_EQP_SWD_380"},
		{L"Clan Mei Sword",L"ITM_EQP_SWD_460"},
		{L"Stonesplitter",L"ITM_EQP_SWD_160"},
		{L"Enchanted Edge",L"ITM_EQP_SWD_180"},
		{L"Crescent Saber",L"ITM_EQP_SWD_350"},
		{L"Reaper's Blade",L"ITM_EQP_SWD_430"},
		{L"Quartz Blade",L"ITM_EQP_SWD_260"},
		{L"Warrior's Sword",L"ITM_EQP_SWD_140"},
		{L"Little Crow",L"ITM_EQP_SWD_130"},
		{L"Refined Sword",L"ITM_EQP_SWD_110"},
		{L"Heavy Blade",L"ITM_EQP_SWD_090"},
		{L"Champion's Sword",L"ITM_EQP_SWD_100"},
		{L"Heretic's Greatsword",L"ITM_EQP_SWD_270"},
		{L"Magic Eater",L"ITM_EQP_SWD_120"},
		{L"Silver Sword",L"ITM_EQP_SWD_070"},
		{L"Guard's Saber",L"ITM_EQP_SWD_080"},
		{L"Spirit Scimitar",L"ITM_EQP_SWD_390"},
		{L"Broadsword",L"ITM_EQP_SWD_060"},
		{L"Iron Blade",L"ITM_EQP_SWD_400"},
		{L"Nameless Sword",L"ITM_EQP_SWD_050"},
		{L"Long Sword",L"ITM_EQP_SWD_041"},
		{L"Knight's Sword",L"ITM_EQP_SWD_032"},
		{L"Imitation Sword",L"ITM_EQP_SWD_021"},
		{L"Rotted Sword",L"ITM_EQP_SWD_450"},
		{L"Sword of the Sands",L"ITM_EQP_SWD_010_GST"},
		{L"Desert Blade",L"ITM_EQP_SWD_020"},
		{L"Makeshift Sword",L"ITM_EQP_SWD_010"},
		{L"Warlord's Spear",L"ITM_EQP_LNS_990"},
		{L"Battle-Tested Spear",L"ITM_EQP_LNS_290"},
		{L"Lost Tribe's Spear",L"ITM_EQP_LNS_490"},
		{L"Gravity Lance",L"ITM_EQP_LNS_180"},
		{L"Spear of Strength",L"ITM_EQP_LNS_270"},
		{L"Forbidden Spear",L"ITM_EQP_LNS_280"},
		{L"Fire Dragon's Glaive",L"ITM_EQP_LNS_350"},
		{L"Monster Bone Spear",L"ITM_EQP_LNS_170"},
		{L"Obsidian Lance",L"ITM_EQP_LNS_150"},
		{L"Seraphim Spear",L"ITM_EQP_LNS_240"},
		{L"Venom Lance",L"ITM_EQP_LNS_260"},
		{L"Well-Worn Pole",L"ITM_EQP_LNS_310"},
		{L"Crimson Spear",L"ITM_EQP_LNS_190"},
		{L"Hyperion Spear",L"ITM_EQP_LNS_160"},
		{L"Rare Metal Glaive",L"ITM_EQP_LNS_200"},
		{L"Sea God's Spear",L"ITM_EQP_LNS_250"},
		{L"Nightmare Glaive",L"ITM_EQP_LNS_230"},
		{L"Clan Mei Spear",L"ITM_EQP_LNS_410"},
		{L"Paladin's Lance",L"ITM_EQP_LNS_130"},
		{L"Lightning Glaive",L"ITM_EQP_LNS_140"},
		{L"Scorched Bone Spear",L"ITM_EQP_LNS_220"},
		{L"Heavy Bone Spear",L"ITM_EQP_LNS_120"},
		{L"Matching Trident",L"ITM_EQP_LNS_430"},
		{L"Soldier's Spear",L"ITM_EQP_LNS_110"},
		{L"Fuscina",L"ITM_EQP_LNS_080"},
		{L"Master Harpoon",L"ITM_EQP_LNS_380"},
		{L"Vanguard's Javelin",L"ITM_EQP_LNS_420"},
		{L"Gluttonous Glaive",L"ITM_EQP_LNS_330"},
		{L"Slashing Glaive",L"ITM_EQP_LNS_100"},
		{L"Steel Lance",L"ITM_EQP_LNS_090"},
		{L"Sandstorm Spear",L"ITM_EQP_LNS_070"},
		{L"Spear of Sleep",L"ITM_EQP_LNS_210"},
		{L"War Glaive",L"ITM_EQP_LNS_370"},
		{L"Memorial Harpoon",L"ITM_EQP_LNS_400"},
		{L"Bone Spear",L"ITM_EQP_LNS_060"},
		{L"Lance",L"ITM_EQP_LNS_390"},
		{L"Long Spear",L"ITM_EQP_LNS_050"},
		{L"Spear",L"ITM_EQP_LNS_040"},
		{L"Imitation Spear",L"ITM_EQP_LNS_021"},
		{L"Desert Spear",L"ITM_EQP_LNS_020"},
		{L"Distinguished Lance",L"ITM_EQP_LNS_010_GST"},
		{L"Handmade Spear",L"ITM_EQP_LNS_031"},
		{L"Makeshift Spear",L"ITM_EQP_LNS_010"},
		{L"Dancer's Blade",L"ITM_EQP_DGR_990"},
		{L"Battle-Tested Dagger",L"ITM_EQP_DGR_280"},
		{L"Lost Tribe's Dagger",L"ITM_EQP_DGR_510"},
		{L"Vengeful Knife",L"ITM_EQP_DGR_380"},
		{L"Ruinous Dagger",L"ITM_EQP_DGR_260"},
		{L"Diamond Dagger",L"ITM_EQP_DGR_170"},
		{L"Dagger in the Rough",L"ITM_EQP_DGR_420"},
		{L"Mooneater",L"ITM_EQP_DGR_430"},
		{L"Forbidden Dagger",L"ITM_EQP_DGR_270"},
		{L"Lockpick",L"ITM_EQP_DGR_440"},
		{L"Bloodstained Knife",L"ITM_EQP_DGR_250"},
		{L"Breaker's Blade",L"ITM_EQP_DGR_410"},
		{L"Ornate Dagger",L"ITM_EQP_DGR_180"},
		{L"Dagger of Seclusion",L"ITM_EQP_DGR_190"},
		{L"Assassin's Dagger",L"ITM_EQP_DGR_160"},
		{L"Mysterious Dagger",L"ITM_EQP_DGR_240"},
		{L"Champion Seeker",L"ITM_EQP_DGR_120"},
		{L"Marietta",L"ITM_EQP_DGR_290"},
		{L"Piercing Dagger",L"ITM_EQP_DGR_360"},
		{L"Doombreaker",L"ITM_EQP_DGR_150"},
		{L"Wind Whisperer",L"ITM_EQP_DGR_210"},
		{L"Poison Dagger",L"ITM_EQP_DGR_300"},
		{L"Moonfang",L"ITM_EQP_DGR_390"},
		{L"Obsidian Dagger",L"ITM_EQP_DGR_140"},
		{L"Black Dagger",L"ITM_EQP_DGR_220"},
		{L"Stealthy Knife",L"ITM_EQP_DGR_130"},
		{L"Drifting Dagger",L"ITM_EQP_DGR_320"},
		{L"Stinging Dagger",L"ITM_EQP_DGR_110"},
		{L"Jade Dagger",L"ITM_EQP_DGR_370"},
		{L"Magus Knife",L"ITM_EQP_DGR_350"},
		{L"Crystal Dagger",L"ITM_EQP_DGR_090"},
		{L"Swordbreaker",L"ITM_EQP_DGR_100"},
		{L"Quartz Dagger",L"ITM_EQP_DGR_200"},
		{L"Falcon Knife",L"ITM_EQP_DGR_080"},
		{L"Handbreaker",L"ITM_EQP_DGR_070"},
		{L"Kukri",L"ITM_EQP_DGR_060"},
		{L"Needle Dagger",L"ITM_EQP_DGR_340"},
		{L"Bronze Knife",L"ITM_EQP_DGR_050"},
		{L"Dagger",L"ITM_EQP_DGR_040"},
		{L"Silver-Plated Knife",L"ITM_EQP_DGR_400"},
		{L"Snakebite",L"ITM_EQP_DGR_020_GST"},
		{L"Fruit Knife",L"ITM_EQP_DGR_030"},
		{L"Sharp Stone",L"ITM_EQP_DGR_022"},
		{L"Sharp Stone",L"ITM_EQP_DGR_021"},
		{L"Makeshift Knife",L"ITM_EQP_DGR_010"},
		{L"Lionheart's Axe",L"ITM_EQP_AXE_990"},
		{L"Battle-Tested Axe",L"ITM_EQP_AXE_290"},
		{L"Lost Tribe's Axe",L"ITM_EQP_AXE_490"},
		{L"Reaper's Sickle",L"ITM_EQP_AXE_330"},
		{L"Hero's Axe",L"ITM_EQP_AXE_420"},
		{L"Forbidden Axe",L"ITM_EQP_AXE_280"},
		{L"Flayer's Admonishment",L"ITM_EQP_AXE_430"},
		{L"Royal Guard's Hatchet",L"ITM_EQP_AXE_390"},
		{L"Axe of the Conqueror",L"ITM_EQP_AXE_220"},
		{L"Cleaver of Destruction",L"ITM_EQP_AXE_170"},
		{L"Stupefying Stone Axe",L"ITM_EQP_AXE_340"},
		{L"Icy Axe",L"ITM_EQP_AXE_350"},
		{L"Imperial Axe",L"ITM_EQP_AXE_190"},
		{L"Frontier Axe",L"ITM_EQP_AXE_200"},
		{L"Contaminated Iron Ingot",L"ITM_EQP_AXE_410"},
		{L"Double Tomahawk",L"ITM_EQP_AXE_270"},
		{L"Guardian's Great Axe",L"ITM_EQP_AXE_360"},
		{L"Dark Slasher",L"ITM_EQP_AXE_260"},
		{L"Pirate's Axe",L"ITM_EQP_AXE_150"},
		{L"Platinum Hatchet",L"ITM_EQP_AXE_160"},
		{L"Quartz Axe",L"ITM_EQP_AXE_250"},
		{L"Grand Cleaver",L"ITM_EQP_AXE_120"},
		{L"Bone Cleaver",L"ITM_EQP_AXE_100"},
		{L"Guardian's Axe",L"ITM_EQP_AXE_140"},
		{L"Guillotine's Blade",L"ITM_EQP_AXE_180"},
		{L"Silver Hatchet",L"ITM_EQP_AXE_130"},
		{L"Frost Axe",L"ITM_EQP_AXE_230"},
		{L"Rock Cleaver",L"ITM_EQP_AXE_110"},
		{L"Axe of Avarice",L"ITM_EQP_AXE_300"},
		{L"Helmcleaver",L"ITM_EQP_AXE_210"},
		{L"Strong Axe",L"ITM_EQP_AXE_090"},
		{L"Poisoned Hatchet",L"ITM_EQP_AXE_240"},
		{L"Battle Hatchet",L"ITM_EQP_AXE_080"},
		{L"Guard's Great Axe",L"ITM_EQP_AXE_070"},
		{L"Iron Axe",L"ITM_EQP_AXE_060"},
		{L"War Axe",L"ITM_EQP_AXE_380"},
		{L"Woodcutter's Great Axe",L"ITM_EQP_AXE_050"},
		{L"Beastling's Hatchet",L"ITM_EQP_AXE_370"},
		{L"Handaxe",L"ITM_EQP_AXE_040"},
		{L"Woodcutter's Axe",L"ITM_EQP_AXE_031"},
		{L"Rotted Axe",L"ITM_EQP_AXE_400"},
		{L"Demolition Axe",L"ITM_EQP_AXE_020"},
		{L"Small Axe",L"ITM_EQP_AXE_030"},
		{L"Snake Fang",L"ITM_EQP_AXE_032"},
		{L"Makeshift Axe",L"ITM_EQP_AXE_010"},
		{L"Hunter's Bow",L"ITM_EQP_BOW_990"},
		{L"Battle-Tested Bow",L"ITM_EQP_BOW_280"},
		{L"Lost Tribe's Bow",L"ITM_EQP_BOW_500"},
		{L"Exorcising Bow",L"ITM_EQP_BOW_360"},
		{L"Floyd's Neo Bow",L"ITM_EQP_BOW_380"},
		{L"Befuddling Greatbow",L"ITM_EQP_BOW_350"},
		{L"Forbidden Bow",L"ITM_EQP_BOW_270"},
		{L"Bow of Carnage",L"ITM_EQP_BOW_290"},
		{L"Protector's Bow",L"ITM_EQP_BOW_170"},
		{L"Art of Archery",L"ITM_EQP_BOW_180"},
		{L"Leviathan Greatbow",L"ITM_EQP_BOW_300"},
		{L"Mechanical Bow",L"ITM_EQP_BOW_260"},
		{L"Evening Mist",L"ITM_EQP_BOW_390"},
		{L"Master's Greatbow",L"ITM_EQP_BOW_210"},
		{L"Ancient Bow",L"ITM_EQP_BOW_400"},
		{L"King of Beasts",L"ITM_EQP_BOW_190"},
		{L"Black Bow",L"ITM_EQP_BOW_490"},
		{L"Engagement Bow",L"ITM_EQP_BOW_420"},
		{L"Absolute Zero Bow",L"ITM_EQP_BOW_240"},
		{L"Sniper's Bow",L"ITM_EQP_BOW_150"},
		{L"Expert's Bow",L"ITM_EQP_BOW_160"},
		{L"Raging Beast",L"ITM_EQP_BOW_200"},
		{L"Marksman's Bow",L"ITM_EQP_BOW_140"},
		{L"Battle Bow",L"ITM_EQP_BOW_410"},
		{L"Knight's Greatbow",L"ITM_EQP_BOW_130"},
		{L"Cupid's Bow",L"ITM_EQP_BOW_320"},
		{L"Steel Bow",L"ITM_EQP_BOW_110"},
		{L"Soldier's Bow",L"ITM_EQP_BOW_120"},
		{L"Mirage Bow",L"ITM_EQP_BOW_230"},
		{L"Sailor's Bow",L"ITM_EQP_BOW_100"},
		{L"Assault Bow",L"ITM_EQP_BOW_090"},
		{L"Shadow Bow",L"ITM_EQP_BOW_220"},
		{L"Guard's Greatbow",L"ITM_EQP_BOW_080"},
		{L"Giant Bow",L"ITM_EQP_BOW_370"},
		{L"Composite Bow",L"ITM_EQP_BOW_060"},
		{L"Beastling's Bow",L"ITM_EQP_BOW_050"},
		{L"Shortbow",L"ITM_EQP_BOW_040"},
		{L"Bow",L"ITM_EQP_BOW_020"},
		{L"Handmade Bow",L"ITM_EQP_BOW_030"},
		{L"Makeshift Bow",L"ITM_EQP_BOW_010"},
		{L"Spiritlord's Staff",L"ITM_EQP_ROD_990"},
		{L"Battle-Tested Staff",L"ITM_EQP_ROD_280"},
		{L"Lost Tribe's Staff",L"ITM_EQP_ROD_460"},
		{L"Forbidden Staff",L"ITM_EQP_ROD_270"},
		{L"Sunshadow Staff",L"ITM_EQP_ROD_430"},
		{L"Staff of Carnage",L"ITM_EQP_ROD_290"},
		{L"Diamond Rod",L"ITM_EQP_ROD_190"},
		{L"Great Sage's Staff",L"ITM_EQP_ROD_310"},
		{L"Bellowing Baton",L"ITM_EQP_ROD_490"},
		{L"Sacred Flame Staff",L"ITM_EQP_ROD_410"},
		{L"Rough-Hewn Rod",L"ITM_EQP_ROD_420"},
		{L"Abyssal Rod",L"ITM_EQP_ROD_250"},
		{L"Hallowed Rod",L"ITM_EQP_ROD_240"},
		{L"Ancient Staff",L"ITM_EQP_ROD_200"},
		{L"Yggdrasil Staff",L"ITM_EQP_ROD_180"},
		{L"Psychic Staff",L"ITM_EQP_ROD_370"},
		{L"Wisdom Wand",L"ITM_EQP_ROD_170"},
		{L"Chef's Ladle",L"ITM_EQP_ROD_320"},
		{L"Quartz Rod",L"ITM_EQP_ROD_160"},
		{L"Fortune Wand",L"ITM_EQP_ROD_140"},
		{L"Sapphire Rod",L"ITM_EQP_ROD_120"},
		{L"Jade Staff",L"ITM_EQP_ROD_220"},
		{L"Magus Wand",L"ITM_EQP_ROD_100"},
		{L"Oak Staff",L"ITM_EQP_ROD_390"},
		{L"Magic Breaker",L"ITM_EQP_ROD_230"},
		{L"Aegis Mace",L"ITM_EQP_ROD_130"},
		{L"Conjurer's Staff",L"ITM_EQP_ROD_400"},
		{L"Mage Wand",L"ITM_EQP_ROD_090"},
		{L"Rod of Wisdom",L"ITM_EQP_ROD_150"},
		{L"Lapis Rod",L"ITM_EQP_ROD_080"},
		{L"Light Wand",L"ITM_EQP_ROD_060"},
		{L"Stone Rod",L"ITM_EQP_ROD_380"},
		{L"Wooden Staff",L"ITM_EQP_ROD_050"},
		{L"Mace",L"ITM_EQP_ROD_070"},
		{L"Sinner's Staff",L"ITM_EQP_ROD_340"},
		{L"Pilgrim Rod",L"ITM_EQP_ROD_350"},
		{L"Charm Rod",L"ITM_EQP_ROD_040"},
		{L"Flamebringer's Staff",L"ITM_EQP_ROD_010_GST"},
		{L"Staff of Judgment",L"ITM_EQP_ROD_030"},
		{L"Stick",L"ITM_EQP_ROD_020"},
		{L"Giant's Club",L"ITM_EQP_ROD_260"},
		{L"Morning Star",L"ITM_EQP_ROD_360"},
		{L"Flail",L"ITM_EQP_ROD_110"},
		{L"Makeshift Staff",L"ITM_EQP_ROD_010"},
		{L"Cursed Shield",L"ITM_EQP_SLD_360"},
		{L"Battle-Tested Shield",L"ITM_EQP_SLD_190"},
		{L"Forbidden Shield",L"ITM_EQP_SLD_180"},
		{L"Wise King's Shield",L"ITM_EQP_SLD_310"},
		{L"Shield of Strength",L"ITM_EQP_SLD_300"},
		{L"Giant Shield",L"ITM_EQP_SLD_350"},
		{L"Aegis Shield",L"ITM_EQP_SLD_210"},
		{L"Protector's Shield",L"ITM_EQP_SLD_340"},
		{L"Adamantine Buckler",L"ITM_EQP_SLD_230"},
		{L"Sun Shield",L"ITM_EQP_SLD_280"},
		{L"Quartz Shield",L"ITM_EQP_SLD_290"},
		{L"Swift Shield",L"ITM_EQP_SLD_240"},
		{L"Heavy Greatshield",L"ITM_EQP_SLD_200"},
		{L"Diamond Shield",L"ITM_EQP_SLD_330"},
		{L"Platinum Shield",L"ITM_EQP_SLD_220"},
		{L"Master's Shield",L"ITM_EQP_SLD_370"},
		{L"Shield of Serenity",L"ITM_EQP_SLD_270"},
		{L"Spiked Shield",L"ITM_EQP_SLD_150"},
		{L"Plate Buckler",L"ITM_EQP_SLD_170"},
		{L"Silver Shield",L"ITM_EQP_SLD_140"},
		{L"Crested Greatshield",L"ITM_EQP_SLD_120"},
		{L"Feather Shield",L"ITM_EQP_SLD_160"},
		{L"Shell Buckler",L"ITM_EQP_SLD_130"},
		{L"Guard's Shield",L"ITM_EQP_SLD_100"},
		{L"Sturdy Shield",L"ITM_EQP_SLD_070"},
		{L"Iron Shield",L"ITM_EQP_SLD_110"},
		{L"Rabbit Shield",L"ITM_EQP_SLD_250"},
		{L"Weathered Treasure Shield",L"ITM_EQP_SLD_260"},
		{L"Kite Shield",L"ITM_EQP_SLD_080"},
		{L"Bronze Shield",L"ITM_EQP_SLD_050"},
		{L"Leather Buckler",L"ITM_EQP_SLD_060"},
		{L"Round Shield",L"ITM_EQP_SLD_090"},
		{L"Buckler",L"ITM_EQP_SLD_040"},
		{L"Resplendent Shield",L"ITM_EQP_SLD_031"},
		{L"Gray Shield",L"ITM_EQP_SLD_021"},
		{L"Small Shield",L"ITM_EQP_SLD_030"},
		{L"Wooden Shield",L"ITM_EQP_SLD_032"},
		{L"Bodyguard's Vantage",L"ITM_EQP_SLD_320"},
		{L"Makeshift Shield",L"ITM_EQP_SLD_011"},
		{L"Cursed Helm",L"ITM_EQP_HLM_460"},
		{L"Mechanical Top Hat",L"ITM_EQP_HLM_370"},
		{L"Imperial Helm",L"ITM_EQP_HLM_240"},
		{L"Dragon's Helm",L"ITM_EQP_HLM_320"},
		{L"Gimmick Goggles",L"ITM_EQP_HLM_260"},
		{L"Royal Guard's Helm",L"ITM_EQP_HLM_420"},
		{L"Great Helm",L"ITM_EQP_HLM_220"},
		{L"Art of Disguise",L"ITM_EQP_HLM_400"},
		{L"Mermaid Circlet",L"ITM_EQP_HLM_530"},
		{L"Dazzling Tiara",L"ITM_EQP_HLM_330"},
		{L"Gaudy Hat",L"ITM_EQP_HLM_350"},
		{L"Cloth Headband",L"ITM_EQP_HLM_440"},
		{L"Forgotten Hat",L"ITM_EQP_HLM_250"},
		{L"Antique Ceremonial Mask",L"ITM_EQP_HLM_310"},
		{L"Lighthouse Keeper's Bandana",L"ITM_EQP_HLM_360"},
		{L"Platinum Helm",L"ITM_EQP_HLM_230"},
		{L"Ancient Circlet",L"ITM_EQP_HLM_270"},
		{L"Soldier's Hat",L"ITM_EQP_HLM_450"},
		{L"Fighter's Headband",L"ITM_EQP_HLM_200"},
		{L"Knight's Helm",L"ITM_EQP_HLM_190"},
		{L"Starlight Hat",L"ITM_EQP_HLM_210"},
		{L"Horned Helm",L"ITM_EQP_HLM_170"},
		{L"Worker's Helmet",L"ITM_EQP_HLM_430"},
		{L"Hasty Helm",L"ITM_EQP_HLM_160"},
		{L"Silent Bandana",L"ITM_EQP_HLM_300"},
		{L"Black Cap",L"ITM_EQP_HLM_410"},
		{L"Gelid Helm",L"ITM_EQP_HLM_280"},
		{L"Skull Helm",L"ITM_EQP_HLM_180"},
		{L"Cassius",L"ITM_EQP_HLM_120"},
		{L"Battle Bandana",L"ITM_EQP_HLM_150"},
		{L"Guard's Helm",L"ITM_EQP_HLM_100"},
		{L"Bronze Helm",L"ITM_EQP_HLM_080"},
		{L"Guard's Hat",L"ITM_EQP_HLM_290"},
		{L"Headgear",L"ITM_EQP_HLM_130"},
		{L"Fur Cap",L"ITM_EQP_HLM_060"},
		{L"Hide Hood",L"ITM_EQP_HLM_070"},
		{L"Silver Hairpiece",L"ITM_EQP_HLM_140"},
		{L"Peddler's Feathered Cap",L"ITM_EQP_HLM_340"},
		{L"Feathered Hat",L"ITM_EQP_HLM_090"},
		{L"Pointed Hat",L"ITM_EQP_HLM_110"},
		{L"Festival Garland",L"ITM_EQP_HLM_050"},
		{L"Sanctum Knight's Helm",L"ITM_EQP_HLM_032"},
		{L"Leather Helm",L"ITM_EQP_HLM_040"},
		{L"Pathfinder's Hat",L"ITM_EQP_HLM_380"},
		{L"Cloth Hood",L"ITM_EQP_HLM_390"},
		{L"Gray Helm",L"ITM_EQP_HLM_010"},
		{L"Black Hood",L"ITM_EQP_HLM_033"},
		{L"Leather Hat",L"ITM_EQP_HLM_021"},
		{L"Ordinary Hat",L"ITM_EQP_HLM_031"},
		{L"Cursed Armor",L"ITM_EQP_AMR_550"},
		{L"Dragon Mail",L"ITM_EQP_AMR_400"},
		{L"Desert Plate",L"ITM_EQP_AMR_330"},
		{L"Sublime Ornamental Armor",L"ITM_EQP_AMR_470"},
		{L"Vest of Joy",L"ITM_EQP_AMR_370"},
		{L"Imperial Armor",L"ITM_EQP_AMR_430"},
		{L"Royal Guard's Mail",L"ITM_EQP_AMR_520"},
		{L"Star's Gown",L"ITM_EQP_AMR_650"},
		{L"Quartz Robe",L"ITM_EQP_AMR_310"},
		{L"Quick Cloak",L"ITM_EQP_AMR_300"},
		{L"Blessed Vestments",L"ITM_EQP_AMR_540"},
		{L"Resplendent Costume",L"ITM_EQP_AMR_390"},
		{L"Butler's Tailcoat",L"ITM_EQP_AMR_450"},
		{L"Lightning Armor",L"ITM_EQP_AMR_380"},
		{L"Conjurer's Raiment",L"ITM_EQP_AMR_460"},
		{L"Ornate Costume",L"ITM_EQP_AMR_320"},
		{L"Antique Coat",L"ITM_EQP_AMR_410"},
		{L"Protector's Vestments",L"ITM_EQP_AMR_530"},
		{L"Platinum Mail",L"ITM_EQP_AMR_290"},
		{L"Knight's Armor",L"ITM_EQP_AMR_260"},
		{L"Desert Armor",L"ITM_EQP_AMR_570"},
		{L"Mage's Robe",L"ITM_EQP_AMR_270"},
		{L"White Wolf Scarf",L"ITM_EQP_AMR_500"},
		{L"Bone Mail",L"ITM_EQP_AMR_360"},
		{L"Acrobat's Mantle",L"ITM_EQP_AMR_250"},
		{L"Nimble Mantle",L"ITM_EQP_AMR_210"},
		{L"Denim Work Clothes",L"ITM_EQP_AMR_280"},
		{L"Dojo Hakama",L"ITM_EQP_AMR_220"},
		{L"Dyed Clothes",L"ITM_EQP_AMR_440"},
		{L"Elemental Robe",L"ITM_EQP_AMR_230"},
		{L"Falcon Coat",L"ITM_EQP_AMR_240"},
		{L"Gorgeous Sari",L"ITM_EQP_AMR_490"},
		{L"Iron Mail",L"ITM_EQP_AMR_190"},
		{L"Guard's Armor",L"ITM_EQP_AMR_150"},
		{L"Beastling Battle Armor",L"ITM_EQP_AMR_420"},
		{L"Sailor's Vest",L"ITM_EQP_AMR_180"},
		{L"Wind Robe",L"ITM_EQP_AMR_350"},
		{L"Copper Breastplate",L"ITM_EQP_AMR_100"},
		{L"Hunting Attire",L"ITM_EQP_AMR_120"},
		{L"Quality Vest",L"ITM_EQP_AMR_480"},
		{L"Fur Robe",L"ITM_EQP_AMR_140"},
		{L"Pilgrim's Robe",L"ITM_EQP_AMR_110"},
		{L"Simple Costume",L"ITM_EQP_AMR_340"},
		{L"Feather Mantle",L"ITM_EQP_AMR_160"},
		{L"Champion's Garb",L"ITM_EQP_AMR_170"},
		{L"Charm Robe",L"ITM_EQP_AMR_200"},
		{L"Sanctum Knight's Armor",L"ITM_EQP_AMR_041"},
		{L"Fur Armor",L"ITM_EQP_AMR_090"},
		{L"Old Armor",L"ITM_EQP_AMR_560"},
		{L"Worker's Jacket",L"ITM_EQP_AMR_510"},
		{L"Desert Attire",L"ITM_EQP_AMR_010"},
		{L"Frog Membrane",L"ITM_EQP_AMR_040"},
		{L"Prisoner's Clothes",L"ITM_EQP_AMR_021"},
		{L"Black Attire",L"ITM_EQP_AMR_070"},
		{L"Robe",L"ITM_EQP_AMR_060"},
		{L"Apothecary's Attire",L"ITM_EQP_AMR_031"},
		{L"Villager's Clothes",L"ITM_EQP_AMR_080"},
		{L"Spurning Ribbon",L"ITM_EQP_ACS_031"},
		{L"Alluring Ribbon",L"ITM_EQP_ACS_041"},
		{L"JP Augmentor",L"ITM_EQP_ACS_060"},
		{L"Brooch of Joy",L"ITM_EQP_ACS_061"},
		{L"Cait Powder",L"ITM_EQP_ACS_660"},
		{L"Octopuff Pot",L"ITM_EQP_ACS_670"},
		{L"Dragon's Scarf",L"ITM_EQP_ACS_011"},
		{L"Beastly Scarf",L"ITM_EQP_ACS_021"},
		{L"Warding Necklace",L"ITM_EQP_ACS_850"},
		{L"Divine Necklace",L"ITM_EQP_ACS_930"},
		{L"Melia's Amulet",L"ITM_EQP_ACS_680"},
		{L"Enfeebling Amulet",L"ITM_EQP_ACS_700"},
		{L"Prosperity Charm",L"ITM_EQP_ACS_710"},
		{L"Charm of Compassion",L"ITM_EQP_ACS_720"},
		{L"Blessing in Disguise",L"ITM_EQP_ACS_890"},
		{L"Finisher's Claws",L"ITM_EQP_ACS_940"},
		{L"Stone of Truth",L"ITM_EQP_ACS_950"},
		{L"Fang of Ferocity",L"ITM_EQP_ACS_960"},
		{L"Gale Feather",L"ITM_EQP_ACS_900"},
		{L"Eye of Calamity",L"ITM_EQP_ACS_910"},
		{L"Victory Ring",L"ITM_EQP_ACS_690"},
		{L"Hand-Sewn Gloves",L"ITM_EQP_ACS_920"},
		{L"Foreign Ring",L"ITM_EQP_ACS_870"},
		{L"Alpione's Amulet",L"ITM_EQP_ACS_730"},
		{L"Librarian's Amulet",L"ITM_EQP_ACS_740"},
		{L"Champion's Belt",L"ITM_EQP_ACS_750"},
		{L"Mikka's Amulet",L"ITM_EQP_ACS_790"},
		{L"Laila's Amulet",L"ITM_EQP_ACS_800"},
		{L"Sisters' Amulet",L"ITM_EQP_ACS_810"},
		{L"Jade Ring",L"ITM_EQP_ACS_880"},
		{L"Shadowsage Necklace",L"ITM_EQP_ACS_860"},
		{L"Rosary of Redemption",L"ITM_EQP_ACS_830"},
		{L"Coat of Arms",L"ITM_EQP_ACS_820"},
		{L"Blazon of Protection",L"ITM_EQP_ACS_260"},
		{L"Scarlet Stone of Protection",L"ITM_EQP_ACS_840"},
		{L"Crescent Moon Necklace",L"ITM_EQP_ACS_970"},
		{L"Moonshell Necklace",L"ITM_EQP_ACS_980"},
		{L"Moonshell Bracelet",L"ITM_EQP_ACS_990"},
		{L"Physical Belt",L"ITM_EQP_ACS_220"},
		{L"Mental Belt",L"ITM_EQP_ACS_230"},
		{L"Mighty Belt",L"ITM_EQP_ACS_240"},
		{L"Elemental Augmentor",L"ITM_EQP_ACS_250"},
		{L"Guardian Amulet",L"ITM_EQP_ACS_340"},
		{L"Elemental Ward",L"ITM_EQP_ACS_350"},
		{L"Empowering Necklace",L"ITM_EQP_ACS_070"},
		{L"Stimulating Necklace",L"ITM_EQP_ACS_080"},
		{L"Protective Necklace",L"ITM_EQP_ACS_090"},
		{L"Unerring Necklace",L"ITM_EQP_ACS_100"},
		{L"Enlightening Necklace",L"ITM_EQP_ACS_110"},
		{L"Sprightly Necklace",L"ITM_EQP_ACS_120"},
		{L"Critical Necklace",L"ITM_EQP_ACS_130"},
		{L"Empowering Bracelet",L"ITM_EQP_ACS_150"},
		{L"Stimulating Bracelet",L"ITM_EQP_ACS_160"},
		{L"Protective Bracelet",L"ITM_EQP_ACS_170"},
		{L"Unerring Bracelet",L"ITM_EQP_ACS_180"},
		{L"Enlightening Bracelet",L"ITM_EQP_ACS_190"},
		{L"Sprightly Bracelet",L"ITM_EQP_ACS_200"},
		{L"Critical Bracelet",L"ITM_EQP_ACS_210"},
		{L"Empowering Ring",L"ITM_EQP_ACS_270"},
		{L"Stimulating Ring",L"ITM_EQP_ACS_280"},
		{L"Protective Ring",L"ITM_EQP_ACS_290"},
		{L"Unerring Ring",L"ITM_EQP_ACS_300"},
		{L"Enlightening Ring",L"ITM_EQP_ACS_310"},
		{L"Sprightly Ring",L"ITM_EQP_ACS_320"},
		{L"Critical Ring",L"ITM_EQP_ACS_330"},
		{L"Falcon Ring",L"ITM_EQP_ACS_780"},
		{L"Empowering Earring",L"ITM_EQP_ACS_360"},
		{L"Stimulating Earring",L"ITM_EQP_ACS_370"},
		{L"Protective Earring",L"ITM_EQP_ACS_380"},
		{L"Unerring Earring",L"ITM_EQP_ACS_390"},
		{L"Enlightening Earring",L"ITM_EQP_ACS_400"},
		{L"Sprightly Earring",L"ITM_EQP_ACS_410"},
		{L"Critical Earring",L"ITM_EQP_ACS_420"},
		{L"Ancient Necklace",L"ITM_EQP_ACS_760"},
		{L"Wargod's Talisman",L"ITM_EQP_ACS_450"},
		{L"Silver Locket",L"ITM_EQP_ACS_440"},
		{L"Angel's Ring",L"ITM_EQP_ACS_770"},
		{L"Inferno Amulet",L"ITM_EQP_ACS_460"},
		{L"Blizzard Amulet",L"ITM_EQP_ACS_470"},
		{L"Void Amulet",L"ITM_EQP_ACS_500"},
		{L"Gleaming Amulet",L"ITM_EQP_ACS_510"},
		{L"Fire Amulet",L"ITM_EQP_ACS_520"},
		{L"Ice Amulet",L"ITM_EQP_ACS_530"},
		{L"Wind Amulet",L"ITM_EQP_ACS_540"},
		{L"Lightning Amulet",L"ITM_EQP_ACS_550"},
		{L"Dark Amulet",L"ITM_EQP_ACS_560"},
		{L"Light Amulet",L"ITM_EQP_ACS_570"},
		{L"Antidote Stone",L"ITM_EQP_ACS_580"},
		{L"Wakeful Stone",L"ITM_EQP_ACS_590"},
		{L"Articulate Stone",L"ITM_EQP_ACS_600"},
		{L"Bright Stone",L"ITM_EQP_ACS_610"},
		{L"Calming Stone",L"ITM_EQP_ACS_620"},
		{L"Clarity Stone",L"ITM_EQP_ACS_630"},
		{L"Conscious Stone",L"ITM_EQP_ACS_640"},
		{L"Vivifying Stone",L"ITM_EQP_ACS_650"},
		{L"Cloudy Mirror",L"ITM_TRE_COP_ST2_0020"},
		{L"Shiny Mirror",L"ITM_TRE_COP_ST2_0030"},
		{L"Oboro's Journal",L"ITM_TRE_END_2D_0010"},
		{L"Journal Fragment I",L"ITM_TRE_END_2B_0010"},
		{L"Journal Fragment II",L"ITM_TRE_END_2B_0020"},
		{L"Journal Fragment III",L"ITM_TRE_END_2B_0030"},
		{L"Journal Fragment IV",L"ITM_TRE_END_2B_0040"},
		{L"Journal Fragment V",L"ITM_TRE_END_2B_0050"},
		{L"Journal Fragment VI",L"ITM_TRE_END_2B_0060"},
		{L"Journal Fragment VII",L"ITM_TRE_END_2B_0070"},
		{L"Journal Fragment VIII",L"ITM_TRE_END_2B_0080"},
		{L"Journal Fragment IX",L"ITM_TRE_END_2B_0090"},
		{L"Journal Fragment X",L"ITM_TRE_END_2B_0100"},
		{L"Journal Fragment XI",L"ITM_TRE_END_2B_0110"},
		{L"Journal Fragment XII",L"ITM_TRE_END_2B_0120"},
		{L"Journal Fragment XIII",L"ITM_TRE_END_2B_0130"},
		{L"Journal Fragment XIV",L"ITM_TRE_END_2B_0140"},
		{L"Journal Fragment XV",L"ITM_TRE_END_2B_0150"},
		{L"Journal Fragment XVI",L"ITM_TRE_END_2B_0160"},
		{L"Journal Fragment XVII",L"ITM_TRE_END_2B_0170"},
		{L"Dancer's Journal",L"ITM_TRE_Oth_01"},
		{L"Worn Journal",L"ITM_TRE_SS_TW21_0200_0020"},
		{L"Wine Offering",L"ITM_TRE_COP_OK2_0010"},
		{L"Sacred Wood",L"ITM_TRE_COP_OK2_0020"},
		{L"Dancer's Mask",L"ITM_TRE_COP_OK2_0030"},
		{L"Folded Paper",L"ITM_TRE_COP_ST2_0010"},
		{L"Improved Telescope",L"ITM_TRE_COP_GS2_0010"},
		{L"Horse Tail Hair",L"ITM_TRE_COP_OK1_0010"},
		{L"Cloudy Mirror Fragment",L"ITM_TRE_COP_ST1_0010"},
		{L"Metalworking Tool",L"ITM_TRE_COP_GS1_0010"},
		{L"Mirror",L"ITM_TRE_COP_GS1_0020"},
		{L"Precision Lens",L"ITM_TRE_COP_GS1_0030"},
		{L"Purebalm",L"ITM_TRE_KUS_50_0010"},
		{L"Scalebark Leaf",L"ITM_TRE_KUS_50_0020"},
		{L"Skybalm",L"ITM_TRE_KUS_50_0030"},
		{L"Santanejo",L"ITM_TRE_KUS_50_0040"},
		{L"Snowdrop",L"ITM_TRE_KUS_50_0050"},
		{L"Black Crystal",L"ITM_TRE_GAK_50_0010"},
		{L"Contract",L"ITM_TRE_SHO_40_0010"},
		{L"Key to Freedom",L"ITM_TRE_TOU_40_0010"},
		{L"Grand Gala Invitation",L"ITM_TRE_ODO_40_0020"},
		{L"Cute Shoes",L"ITM_TRE_ODO_40_0010"},
		{L"Silverwork",L"ITM_TRE_SHO_30_0050"},
		{L"Pocket Watch",L"ITM_TRE_SHO_30_0040"},
		{L"Quality Paper",L"ITM_TRE_SHO_30_0030"},
		{L"Special Wheat Flour",L"ITM_TRE_SHO_30_0020"},
		{L"Coffee Beans",L"ITM_TRE_SHO_30_0010"},
		{L"Kaldena's Notebook",L"ITM_TRE_SIN_3B_0030"},
		{L"Mysterious Notebook",L"ITM_TRE_SIN_3B_0020"},
		{L"Crescent Moon Necklace",L"ITM_TRE_SIN_3B_0010"},
		{L"Father's Key",L"ITM_TRE_TOU_3B_0010"},
		{L"Mother's Key",L"ITM_TRE_TOU_3A_0030"},
		{L"Mother's Garden Key",L"ITM_TRE_TOU_3A_0020"},
		{L"Habit",L"ITM_TRE_TOU_3A_0010"},
		{L"Wooden Sword",L"ITM_TRE_ODO_30_0010"},
		{L"Aromatic Jerky",L"ITM_TRE_KAR_2B_0010"},
		{L"Rosa's Medicine",L"ITM_TRE_KUS_2B_0040"},
		{L"Bloodberry",L"ITM_TRE_KUS_2B_0030"},
		{L"Snowgrass",L"ITM_TRE_KUS_2B_0020"},
		{L"Scalebark Leaf",L"ITM_TRE_KUS_2B_0010"},
		{L"Clockite",L"ITM_TRE_SHO_20_0010"},
		{L"Mask",L"ITM_TRE_TOU_2A_0020"},
		{L"Horse Coin",L"ITM_TRE_TOU_2A_0010"},
		{L"Ship Alteration Ticket",L"ITM_TRE_SHO_EX1_0020"},
		{L"Unfinished Vessel",L"ITM_TRE_SHO_EX1_0030"},
		{L"Mercantile Manuscript Archive Key",L"ITM_TRE_SHO_EX3_0010"},
		{L"Friendship Jerky",L"ITM_TRE_KAR_10_0010"},
		{L"Apothecary's Satchel",L"ITM_TRE_KUS_10_0020"},
		{L"Snowdrop Flower",L"ITM_TRE_KUS_30_0010"},
		{L"White Flower",L"ITM_TRE_KUS_10_0010"},
		{L"Lychanthe Antipyretic",L"ITM_TRE_KUS_10_0030"},
		{L"Papp's Medicine",L"ITM_TRE_SHO_10_0020"},
		{L"Earnings",L"ITM_TRE_SHO_10_0050"},
		{L"Dubious Silver Nugget",L"ITM_TRE_SHO_10_0010"},
		{L"Book of Scripture",L"ITM_TRE_SIN_10_0030"},
		{L"Labor Report",L"ITM_TRE_GAK_10_0020"},
		{L"Cold-Weather Wear",L"ITM_TRE_GAK_10_0030"},
		{L"Osvald's Notebook",L"ITM_TRE_GAK_10_0010"},
		{L"Brothel Girl's Clothes",L"ITM_TRE_TOU_10_0010"},
		{L"Mama's Dress",L"ITM_TRE_ODO_10_0030"},
		{L"Merchant License",L"ITM_EQP_JOB_0000"},
		{L"Warrior License",L"ITM_EQP_JOB_0002"},
		{L"Hunter License",L"ITM_EQP_JOB_0003"},
		{L"Cleric License",L"ITM_EQP_JOB_0004"},
		{L"Dancer License",L"ITM_EQP_JOB_0005"},
		{L"Scholar License",L"ITM_EQP_JOB_0006"},
		{L"Apothecary License",L"ITM_EQP_JOB_0007"},
		{L"Proof of the Armsmaster",L"ITM_EQP_JOB_0008"},
		{L"Proof of the Arcanist",L"ITM_EQP_JOB_0009"},
		{L"Proof of the Conjurer",L"ITM_EQP_JOB_0010"},
		{L"Proof of the Inventor",L"ITM_EQP_JOB_0011"},
		{L"1. Cait's Theme –Piano Version–",L"ITM_TRE_RECORD_001"},
		{L"2. Cait's Theme –Guitar Version–",L"ITM_TRE_RECORD_002"},
		{L"3. Cait's Theme –Violin Version–",L"ITM_TRE_RECORD_003"},
		{L"4. Ochette, the Hunter",L"ITM_TRE_RECORD_007"},
		{L"5. Castti, the Apothecary",L"ITM_TRE_RECORD_005"},
		{L"6. Throné, the Thief",L"ITM_TRE_RECORD_006"},
		{L"7. Osvald, the Scholar",L"ITM_TRE_RECORD_004"},
		{L"8. Partitio, the Merchant",L"ITM_TRE_RECORD_008"},
		{L"9. Agnea, the Dancer",L"ITM_TRE_RECORD_009"},
		{L"10. Temenos, the Cleric",L"ITM_TRE_RECORD_010"},
		{L"11. Hikari, the Warrior",L"ITM_TRE_RECORD_011"},
		{L"12. Normal Battle I",L"ITM_TRE_RECORD_012"},
		{L"13. Normal Battle II",L"ITM_TRE_RECORD_013"},
		{L"14. Normal Battle III",L"ITM_TRE_RECORD_014"},
		{L"15. Battle on the Sea",L"ITM_TRE_RECORD_015"},
		{L"16. Critical Clash I",L"ITM_TRE_RECORD_016"},
		{L"17. Critical Clash II",L"ITM_TRE_RECORD_017"},
		{L"18. Miscreant's Melody",L"ITM_TRE_RECORD_018"},
		{L"19. Soliloquy",L"ITM_TRE_RECORD_019"},
		{L"20. Carefree Days",L"ITM_TRE_RECORD_020"},
		{L"21. Unshakable Resolve",L"ITM_TRE_RECORD_021"},
		{L"22. Bygone Days",L"ITM_TRE_RECORD_022"},
		{L"23. At Your Back",L"ITM_TRE_RECORD_023"},
		{L"24. Hope",L"ITM_TRE_RECORD_024"},
		{L"25. Oresrush, Dried Up",L"ITM_TRE_RECORD_025"},
		{L"26. Oresrush, Dried Up –Night–",L"ITM_TRE_RECORD_026"},
		{L"27. The Journey Begins",L"ITM_TRE_RECORD_027"},
		{L"28. All For You",L"ITM_TRE_RECORD_028"},
		{L"29. Gil on the Keys",L"ITM_TRE_RECORD_029"},
		{L"30. Scarlet Folk Song –By the Light of the Heart–",L"ITM_TRE_RECORD_030"},
		{L"Master Thief's Sapphire Stone",L"ITM_TRE_GLD_02"},
		{L"High Priest's Amulet",L"ITM_TRE_GLD_03"},
		{L"High Priest's Book of Scripture",L"ITM_TRE_GLD_04"},
		{L"Quicksand Monster's Liver",L"ITM_TRE_GLD_07"},
		{L"Sea Monster's Whisker",L"ITM_TRE_GLD_08"},
		{L"Rusty Sword",L"ITM_TRE_WPM_01"},
		{L"Rusty Polearm",L"ITM_TRE_WPM_02"},
		{L"Rusty Dagger",L"ITM_TRE_WPM_03"},
		{L"Rusty Axe",L"ITM_TRE_WPM_04"},
		{L"Rusty Bow",L"ITM_TRE_WPM_05"},
		{L"Rusty Staff",L"ITM_TRE_WPM_06"},
		{L"Changeable Catapult Design",L"ITM_TRE_INV_01"},
		{L"Springy Boots Design",L"ITM_TRE_INV_02"},
		{L"Critical Scope Design",L"ITM_TRE_INV_03"},
		{L"Elemental Bomb Bottle Design",L"ITM_TRE_INV_04"},
		{L"Hastening Hammer Design",L"ITM_TRE_INV_06"},
		{L"Arkar's Coil Design",L"ITM_TRE_INV_07"},
		{L"All-Purpose Tool Design",L"ITM_TRE_INV_08"},
		{L"Rainbow Glass Bottle",L"ITM_TRE_INV_PARTS_01"},
		{L"Mythical Horn",L"ITM_TRE_INV_PARTS_02"},
		{L"Scrap Metal",L"ITM_TRE_INV_PARTS_04"},
		{L"Ancient Cog",L"ITM_TRE_INV_PARTS_05"},
		{L"Natural Magnetite",L"ITM_TRE_INV_PARTS_06"},
		{L"Letter from the Snowhares",L"ITM_TRE_JNP_MEL_0010"},
		{L"Lute",L"ITM_TRE_JNP_MOR_0010"},
		{L"Paper Play",L"ITM_TRE_JNP_MOR_0020"},
		{L"History Book",L"ITM_TRE_JNP_MOR_0030"},
		{L"Earrings",L"ITM_TRE_JNP_MIK_0010"},
		{L"Sacred Flame Candle",L"ITM_TRE_SS_TM12_0100_0010"},
		{L"Dispatches from Beastling Island",L"ITM_TRE_SS_TM21_0200_0010"},
		{L"From the Far Reaches of Hell",L"ITM_TRE_SS_TM21_0200_0030"},
		{L"Keepsake Sword",L"ITM_TRE_SS_TD21_0100_0010"},
		{L"Fort Orochi Plans",L"ITM_TRE_SS_TD21_0200_0010"},
		{L"Dragon Vase",L"ITM_TRE_SS_TD31_0200_0010"},
		{L"Phoenix Fan",L"ITM_TRE_SS_TD31_0200_0020"},
		{L"Miracle Stone",L"ITM_TRE_SS_TC11_0400_0010"},
		{L"Special Bait",L"ITM_TRE_SS_TC11_0500_0010"},
		{L"Delsta Devil",L"ITM_TRE_SS_TC11_0500_0020"},
		{L"Nyx Royal Family Tree",L"ITM_TRE_SS_TC21_0200_0010"},
		{L"Amulet of Affection",L"ITM_TRE_SS_TI11_0100_0010"},
		{L"Pretty Pearl",L"ITM_TRE_SS_TI21_0200_0010"},
		{L"Stocked Goods",L"ITM_TRE_SS_TW11_0100_0010"},
		{L"Mysterious Box",L"ITM_TRE_SS_TW21_0200_0010"},
		{L"Bottle of White Powder",L"ITM_TRE_SS_TSe11_0200_0010"},
		{L"Deluxe Crepe",L"ITM_TRE_SS_TSe21_0300_0010"},
		{L"Message in a Bottle",L"ITM_TRE_SS_TSe21_0400_0010"},
		{L"Crop Tapestry Pattern",L"ITM_TRE_SS_TF11_0100_0010"},
		{L"Azure Sun Sword",L"ITM_TRE_SS_TF31_0200_0010"},
		{L"Silver Quill",L"ITM_TRE_SS_TSn21_0100_0010"},
		{L"Cloudy Crystal Bracelet",L"ITM_TRE_SS_TW31_0200_0010"},
		{L"Aelmorite Reflector",L"ITM_TRE_SS_TSe11_0300_0010"},
		{L"Sturdy Pickaxe",L"ITM_TRE_SS_TSn21_0200_0010"},
		{L"Al's Bag",L"ITM_TRE_SS_TD11_0100_0010"},
		{L"Stolen Sword",L"ITM_TRE_SS_TF31_0400_0010"},
		{L"Wallet",L"ITM_TRE_ODO_00_0010"},
		{L"Escape Route Map",L"ITM_TRE_JNP_BND_0010"},
		{L"Grape Leaf",L"ITM_MRL_REV_0010"},
		{L"Plum Leaf",L"ITM_MRL_REV_0020"},
		{L"Pomegranate Leaf",L"ITM_MRL_REV_0030"},
		{L"Mighty Leaf",L"ITM_MRL_REV_0040"},
		{L"Fool's Leaf",L"ITM_MRL_REV_0050"},
		{L"Cleansing Leaf",L"ITM_MRL_REV_0060"},
		{L"Warding Leaf",L"ITM_MRL_REV_0070"},
		{L"Whimsical Leaf",L"ITM_MRL_REV_0080"},
		{L"Dual Leaf",L"ITM_MRL_REV_0090"},
		{L"Weeds",L"ITM_MRL_REV_0100"},
		{L"Blusterbloom",L"ITM_MRL_ATK_0010"},
		{L"Lily of the Light",L"ITM_MRL_ATK_0020"},
		{L"Darkdelion",L"ITM_MRL_ATK_0030"},
		{L"Forget-Me-Do",L"ITM_MRL_ATK_0040"},
		{L"Sticky Flower",L"ITM_MRL_ATK_0050"},
		{L"Fumbling Flower",L"ITM_MRL_ATK_0060"},
		{L"Dreamy Flower",L"ITM_MRL_ATK_0070"},
		{L"Enfeebling Flower",L"ITM_MRL_ATK_0080"},
		{L"Dual Flower",L"ITM_MRL_ATK_0090"},
		{L"Weeds",L"ITM_MRL_ATK_0100"},
		{L"Diffusing Serum",L"ITM_MRL_COM_0010"},
		{L"Strengthening Serum",L"ITM_MRL_COM_0020"},
		{L"Bale's Weakness",L"ITM_INF_GAK_10_0100"},
		{L"Labor Report Whereabouts",L"ITM_INF_GAK_10_0200"},
		{L"An Eyewitness to Harvey",L"ITM_INF_GAK_40_05A0"},
		{L"Library Rumor",L"ITM_INF_GAK_40_05B0"},
		{L"Harvey's Whereabouts",L"ITM_INF_GAK_40_05C0"},
		{L"Hunting Request",L"ITM_INF_JNP_APN_0100"},
		{L"Garbage Collector",L"ITM_INF_JNP_SHI_0100"},
		{L"Man in a Brown Coat",L"ITM_INF_JNP_SHI_0200"},
		{L"Dolcinaea and Gifts",L"ITM_INF_JNP_YJB_0100"},
		{L"Castle Merchant's Information",L"ITM_INF_KEN_10_0100"},
		{L"Weapons Deal Details",L"ITM_INF_KEN_30_0100"},
		{L"More Plentiful Provisions",L"ITM_INF_Mnt_1_1_A_SHOP01"},
		{L"Discount at the Inn",L"ITM_INF_Mnt_1_1_A_SHOP04"},
		{L"Guide with Ease",L"ITM_INF_Mnt_1_1_FC_010"},
		{L"Underground Passage to the Cathedral",L"ITM_INF_SHO_10_0100"},
		{L"Lingering Scent of Incense",L"ITM_INF_SIN_10_0100"},
		{L"Shattered Cathedral Window",L"ITM_INF_SIN_10_0200"},
		{L"Lucian's Notebook",L"ITM_INF_SIN_20_0100"},
		{L"Prayer Handbook",L"ITM_INF_SIN_20_0200"},
		{L"Prayer Order",L"ITM_INF_SIN_20_0300"},
		{L"Nyx Family History",L"ITM_INF_SS_TC21_0200_0100"},
		{L"Well Iris Uses",L"ITM_INF_SS_TF21_0100_0100"},
		{L"Margello's Personality",L"ITM_INF_SS_TF31_0300_0100"},
		{L"Spicy Chicken Recipe",L"ITM_INF_SS_TI11_0200_0100"},
		{L"Adventures of an Apprentice Cleric's Sequel",L"ITM_INF_SS_TSe21_0300_0100"},
		{L"Nikki's Special Joke",L"ITM_INF_SS_TW11_0200_0100"},
		{L"Harry's Self-Deprecating Joke",L"ITM_INF_SS_TW11_0200_0200"},
		{L"Ned's Romantic Advice",L"ITM_INF_SS_TW11_0200_0300"},
		{L"A Killer's Motive",L"ITM_INF_SS_TF31_0400_0100"},
		{L"How to Decipher Unknown Languages",L"ITM_INF_SS_TM21_0400_0100"},
		{L"New Equipment for Sale",L"ITM_INF_Twn_Cty_1_1_A_SHOP01"},
		{L"Discount at the Inn",L"ITM_INF_Twn_Cty_1_1_A_SHOP04"},
		{L"New Items for Sale",L"ITM_INF_Twn_Cty_1_1_A_SHOP05"},
		{L"Undeniable Allure",L"ITM_INF_Twn_Cty_1_1_FC_020"},
		{L"Masterful Mugging",L"ITM_INF_Twn_Cty_1_1_FC_030"},
		{L"Hire for Cheap",L"ITM_INF_Twn_Cty_1_1_FC_040"},
		{L"New Equipment for Sale",L"ITM_INF_Twn_Cty_1_2_A_SHOP03"},
		{L"Discount at the Inn",L"ITM_INF_Twn_Cty_1_2_A_SHOP04"},
		{L"New Equipment for Sale",L"ITM_INF_Twn_Cty_2_1_A_SHOP01"},
		{L"Discount at the Inn",L"ITM_INF_Twn_Cty_2_1_B_SHOP04"},
		{L"Hire for Cheap",L"ITM_INF_Twn_Cty_2_1_FC_010"},
		{L"More Plentiful Provisions",L"ITM_INF_Twn_Cty_3_1_A_SHOP01"},
		{L"Discount at the Inn",L"ITM_INF_Twn_Cty_3_1_A_SHOP04"},
		{L"New Equipment for Sale",L"ITM_INF_Twn_Dst_1_1_SHOP01"},
		{L"Discount at the Inn",L"ITM_INF_Twn_Dst_1_1_SHOP04"},
		{L"Challenge with Ease",L"ITM_INF_Twn_Dst_1_1_FC_010"},
		{L"Undeniable Allure",L"ITM_INF_Twn_Dst_1_1_FC_020"},
		{L"New Equipment for Sale",L"ITM_INF_Twn_Dst_2_1_A_SHOP01"},
		{L"Discount at the Inn",L"ITM_INF_Twn_Dst_2_1_A_SHOP04"},
		{L"Challenge with Ease",L"ITM_INF_Twn_Dst_2_1_FC_010"},
		{L"Easier Inquiries",L"ITM_INF_Twn_Dst_2_1_FC_020"},
		{L"New Equipment for Sale",L"ITM_INF_Twn_Dst_3_1_A_SHOP01"},
		{L"Challenge with Ease",L"ITM_INF_Twn_Dst_3_1_FC_010"},
		{L"Undeniable Allure",L"ITM_INF_Twn_Dst_3_1_FC_020"},
		{L"More Plentiful Provisions",L"ITM_INF_Twn_Fst_1_1_A_SHOP01"},
		{L"Discount at the Inn",L"ITM_INF_Twn_Fst_1_1_A_SHOP04"},
		{L"Undeniable Allure",L"ITM_INF_Twn_Fst_1_1_FC_010"},
		{L"Easier Inquiries",L"ITM_INF_Twn_Fst_1_1_FC_020"},
		{L"New Weapons for Sale",L"ITM_INF_Twn_Fst_2_1_C_SHOP01"},
		{L"New Armor for Sale",L"ITM_INF_Twn_Fst_2_1_C_SHOP02"},
		{L"Discount at the Inn",L"ITM_INF_Twn_Fst_2_1_A_SHOP04"},
		{L"Hire for Cheap",L"ITM_INF_Twn_Fst_2_1_FC_010"},
		{L"New Equipment for Sale",L"ITM_INF_Twn_Fst_3_1_A_SHOP01"},
		{L"Discount at the Inn",L"ITM_INF_Twn_Fst_3_1_A_SHOP04"},
		{L"Easier Inquiries",L"ITM_INF_Twn_Fst_3_1_FC_010"},
		{L"Provoke Like a Pro",L"ITM_INF_Twn_Fst_3_1_FC_020"},
		{L"New Equipment for Sale",L"ITM_INF_Twn_Isd_1_1_A_SHOP01"},
		{L"Discount at the Inn",L"ITM_INF_Twn_Isd_1_1_A_SHOP04"},
		{L"Provoke Like a Pro",L"ITM_INF_Twn_Isd_1_1_FC_010"},
		{L"New Equipment for Sale",L"ITM_INF_Twn_Isd_2_1_A_SHOP01"},
		{L"Discount at the Inn",L"ITM_INF_Twn_Isd_2_1_A_SHOP04"},
		{L"Undeniable Allure",L"ITM_INF_Twn_Isd_2_1_FC_010"},
		{L"New Equipment for Sale",L"ITM_INF_Twn_Isd_3_1_A_SHOP01"},
		{L"Discount at the Inn",L"ITM_INF_Twn_Isd_3_1_A_SHOP04"},
		{L"Guide with Ease",L"ITM_INF_Twn_Isd_3_1_FC_010"},
		{L"Provoke Like a Pro",L"ITM_INF_Twn_Isd_3_1_FC_020"},
		{L"Discount at the Inn",L"ITM_INF_Twn_Mnt_2_1_A_SHOP04"},
		{L"New Equipment for Sale",L"ITM_INF_Twn_Mnt_2_1_A_SHOP01"},
		{L"New Equipment for Sale",L"ITM_INF_Twn_Mnt_2_1_C_SHOP01_1"},
		{L"New Equipment for Sale",L"ITM_INF_Twn_Mnt_2_1_C_SHOP01_2"},
		{L"New Equipment for Sale",L"ITM_INF_Twn_Mnt_2_1_C_SHOP01_3"},
		{L"Challenge with Ease",L"ITM_INF_Twn_Mnt_2_1_FC_010"},
		{L"Masterful Mugging",L"ITM_INF_Twn_Mnt_2_1_FC_020"},
		{L"Hire for Cheap",L"ITM_INF_Twn_Mnt_2_1_FC_030"},
		{L"New Equipment for Sale",L"ITM_INF_Twn_Mnt_3_1_A_SHOP01"},
		{L"Discount at the Inn",L"ITM_INF_Twn_Mnt_3_1_A_SHOP04"},
		{L"Undeniable Allure",L"ITM_INF_Twn_Mnt_3_1_FC_010"},
		{L"New Equipment for Sale",L"ITM_INF_Twn_Sea_1_1_A_SHOP01"},
		{L"Discount at the Inn",L"ITM_INF_Twn_Sea_1_1_A_SHOP04"},
		{L"Easier Inquiries",L"ITM_INF_Twn_Sea_1_1_FC_010"},
		{L"Guide with Ease",L"ITM_INF_Twn_Sea_1_1_FC_020"},
		{L"More Plentiful Provisions",L"ITM_INF_Twn_Sea_2_1_A_SHOP01"},
		{L"Discount at the Inn",L"ITM_INF_Twn_Sea_2_1_A_SHOP04"},
		{L"Provoke Like a Pro",L"ITM_INF_Twn_Sea_2_1_FC_010"},
		{L"Masterful Mugging",L"ITM_INF_Twn_Sea_2_1_FC_020"},
		{L"Guide with Ease",L"ITM_INF_Twn_Sea_2_1_FC_030"},
		{L"New Equipment for Sale",L"ITM_INF_Twn_Sea_3_1_A_SHOP01"},
		{L"Discount at the Inn",L"ITM_INF_Twn_Sea_3_1_A_SHOP04"},
		{L"Hire for Cheap",L"ITM_INF_Twn_Sea_3_1_FC_010"},
		{L"Masterful Mugging",L"ITM_INF_Twn_Sea_3_1_FC_020"},
		{L"More Plentiful Provisions",L"ITM_INF_Twn_Snw_1_2_A_SHOP03"},
		{L"Discount at the Inn",L"ITM_INF_Twn_Snw_1_2_A_SHOP04"},
		{L"Masterful Mugging",L"ITM_INF_Twn_Snw_1_2_FC_010"},
		{L"Discount at the Inn",L"ITM_INF_Twn_Snw_2_1_A_SHOP04"},
		{L"New Equipment for Sale",L"ITM_INF_Twn_Snw_2_1_B_SHOP01"},
		{L"Easier Inquiries",L"ITM_INF_Twn_Snw_2_1_FC_010"},
		{L"New Equipment for Sale",L"ITM_INF_Twn_Snw_3_1_A_SHOP01"},
		{L"Discount at the Inn",L"ITM_INF_Twn_Snw_3_1_A_SHOP04"},
		{L"Challenge with Ease",L"ITM_INF_Twn_Snw_3_1_FC_010"},
		{L"Guide with Ease",L"ITM_INF_Twn_Snw_3_1_FC_020"},
		{L"Easier Inquiries",L"ITM_INF_Twn_Snw_3_1_FC_030"},
		{L"New Equipment for Sale",L"ITM_INF_Twn_Wld_2_1_A_SHOP01"},
		{L"Discount at the Inn",L"ITM_INF_Twn_Wld_2_1_A_SHOP04"},
		{L"Provoke Like a Pro",L"ITM_INF_Twn_Wld_2_1_FC_010"},
		{L"Guide with Ease",L"ITM_INF_Twn_Wld_2_1_FC_020"},
		{L"New Equipment for Sale",L"ITM_INF_Twn_Wld_3_1_A_SHOP01"},
		{L"Discount at the Inn",L"ITM_INF_Twn_Wld_3_1_A_SHOP04"},
		{L"Masterful Mugging",L"ITM_INF_Twn_Wld_3_1_FC_010"},
		{L"Hire for Cheap",L"ITM_INF_Twn_Wld_3_1_FC_020"},
		{L"New Equipment for Sale",L"ITM_INF_Wld_1_1_C_SHOP01"},
		{L"Discount at the Inn",L"ITM_INF_Wld_1_1_C_SHOP04"},
		{L"Hire for Cheap",L"ITM_INF_Wld_1_1_C_FC_010"},
		{L"Medicinal Herbs",L"ITM_INF_KUS_2B_0100"},
		{L"None",L"ITM_MONEY_000"},
		{L"Jerky",L"ITM_MEAT_1280"},
		{L"Quality Jerky",L"ITM_MEAT_1290"},
		{L"Superior Jerky",L"ITM_MEAT_1300"},
		{L"Aromatic Jerky",L"ITM_MEAT_1530"},
		{L"Snowy Stew",L"ITM_MEAT_1310"},
		{L"Mountain Sausage",L"ITM_MEAT_1320"},
		{L"Island Skewer",L"ITM_MEAT_1340"},
		{L"Seafood Paella",L"ITM_MEAT_1350"},
		{L"Spicy Offal Stew",L"ITM_MEAT_1360"},
		{L"Wild Steak",L"ITM_MEAT_1370"},
		{L"Breezy Beef Stew",L"ITM_MEAT_1380"},
		{L"Grilled Chicken",L"ITM_MEAT_1390"},
		{L"Beast Liver",L"ITM_MEAT_1400"},
		{L"Creamy Saute",L"ITM_MEAT_1410"},
		{L"Salted Seafood",L"ITM_MEAT_1420"},
		{L"Bone",L"ITM_MEAT_1430"},
		{L"Metal Medley",L"ITM_MEAT_1440"},
		{L"Stone-Roasted Rice",L"ITM_MEAT_1450"},
		{L"Salad",L"ITM_MEAT_1460"},
		{L"Elemental Soup",L"ITM_MEAT_1470"},
		{L"Spicy Jerky",L"ITM_MEAT_1480"},
		{L"Rotten Meat",L"ITM_MEAT_1490"},
		{L"Perfect Jerky",L"ITM_MEAT_1500"},
		{L"Jewel Cake",L"ITM_MEAT_1510"},
		{L"Octopath Bowl",L"ITM_MEAT_1520"},
	};
}